FROM centos:latest

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat
RUN curl -O https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
RUN tar xvfz apache-tomcat-8.5.61.tar.gz
RUN mv apache-tomcat-8.5.61/* /opt/tomcat/.
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps

RUN curl -O -L https://github.com/AKSarav/SampleWebApp/raw/master/dist/SampleWebApp.war

WORKDIR /opt/tomcat/bin

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]